language: cpp

compiler:
  - gcc
  
before_install:
  - sudo apt-get update
  - sudo apt-get install --yes build-essential
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

branches:
  only:
    - master