language: cpp

os:
  - linux
  - osx

dist: xenial
sudo: required

osx_image: xcode10.1

before_install:
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo add-apt-repository --yes ppa:beineri/opt-qt-5.12.2-xenial; fi
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo apt-get -qq update; fi
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo apt-get install -y libzmq3-dev libzmqpp-dev; fi
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo apt-get install -y qt512webengine qt512webchannel qt512svg qt512base qt512location qt512tools libgl1-mesa-dev; fi
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo apt-get install -y libboost-date-time-dev libjsoncpp-dev openssl; fi
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo apt-get install -y ant ant-optional junit; fi
  - if [ ${TRAVIS_OS_NAME} = "osx" ]; then brew update && brew tap caskroom/cask && brew install ant && brew install qt; fi

before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then source /opt/qt512/bin/qt512-env.sh; fi
  - mkdir cmake_build && cd cmake_build
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cmake -DENABLE_CYACAS_KERNEL=Off .. ; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then unset CXX; unset CC; cmake -G Xcode -DCMAKE_PREFIX_PATH=`brew --prefix qt` -DENABLE_CYACAS_KERNEL=Off .. ; fi
  - git clone https://github.com/google/benchmark.git
  - cd benchmark
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_GTEST_TESTS=OFF ..
  - cmake --build . --target install --config Release
  - cd ../..


script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then make; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then make test ; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then travis_wait xcodebuild -project yacas.xcodeproj -target ALL_BUILD; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then xcodebuild -project yacas.xcodeproj -target RUN_TESTS; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then travis_wait xcodebuild -project yacas.xcodeproj -configuration Release -target ALL_BUILD; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then xcodebuild -project yacas.xcodeproj -configuration Release -target RUN_TESTS; fi
  - cd .. && ant && ant test

branches:
  except:
    - gh_pages
    - vendor
    - bignum_experiments
    - coverity_scan
