language: cpp

compiler:
  - gcc
  
before_install:
  - sudo apt-get update
  - sudo apt-get install --yes build-essential
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-4.8 g++-4.8
  - sudo apt-get -qq install oracle-java8-installer oracle-java8-set-default
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 20
  
before_script:
  - mkdir cmake_build
  - cd cmake_build
  - cmake ..

script:
  - make
  - make test
  - cd ..
  - ant
  - ant test

branches:
  only:
    - master