sudo: false

os:
  - linux
  - osx

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "IIinoeFZyP/twtjsKE9Vi7RFdZYKMUW12fS6Pguc5hLokxzmCPgf5TciIeblm/nHnzrPjyyESZf7jkae8hST33nSCWmKg8ZAvlaN5+jbwFLpmZJo7dkwhwUw2FxcbLUzqMPD3TdZpcIPlaZs5eXkeVV/jJal/1geG3ivMCF23Z0ibtT/Kjf8iaFMvHhNqBcQUBQu6lzIDGzRnCgFE13MXNLz/JBuSqy5i45ScVpthTMd+L/uTHHPBsip8/Ow4D9DqM2Kdm339cK8fQtP8l2llCVv2+So4zb2oKTx5FQQy9+aWfkDwWuvGjKG3ge5q0CsdOOT/+/nyj6vLjRQgsoqvmt8d7Ugpm0T08xuBTC+cUVvpVTIhzXhVksXKaf8Y1qtNDjiI1WdS5UXikyEeOCpwBvWkRmrW1x8L+3eYv66DSsAHv0Yc9QDLDg6gy3IVPDY3/Le7FZVXNkgX65Xg1vque64sbf/GXgE1xfOUZ3Waf1AIX6q+cBz8auB2gqiSEbdInXbRmE+o60mROVo5EqrB4pZcQMBBYQu750pc2qaDZho/OaHhbh6ogqhe5PaEPJdxGzoND/e1i4jcgSkVjJBc8lfVosMR7wCn1KMnc1aF/9dZL2H6p9Eha4wcT1fcD/J0Bvg9h8UqQm1jzDQK6MBV3PtvFJOIB49znjWzKHTqpo="

language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
  coverity_scan:
    project:
      name: "grzegorzmazur/yacas"
      description: "Computer calculations made easy"
    notification_email: teoretyk@gmail.com
    build_command_prepend: "cmake ."
    build_command: "make"
    branch_pattern: coverity_scan

before_install:
  - export CC=gcc-4.8 CXX=g++-4.8
  
before_script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mkdir cmake_build ; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then cd cmake_build ; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 -a "${TRAVIS_OS_NAME}" = "linux" ]; then cmake .. ; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 -a "${TRAVIS_OS_NAME}" = "osx" ]; then unset CC; unset CXX; cmake -G Xcode .. ; fi

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 -a "${TRAVIS_OS_NAME}" = "linux" ]; then make; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 -a "${TRAVIS_OS_NAME}" = "linux" ]; then make test ; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 -a "${TRAVIS_OS_NAME}" = "linux" ]; then cd .. ; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 -a "${TRAVIS_OS_NAME}" = "linux" ]; then ant ; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 -a "${TRAVIS_OS_NAME}" = "linux" ]; then ant test ; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 -a "${TRAVIS_OS_NAME}" = "osx" ]; then xcodebuild -list -project yacas.xcodeproj ; fi

branches:
  except:
    - gh_pages
    - vendor
    - bignum_experiments