branches:
  only:
    - master
    - develop

skip_tags: true

platform:
  - x64

configuration:
  - Release

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: "Visual Studio 16 2019"
      ENABLE_CYACAS_GUI: On
      QTDIR: C:\Qt\5.15.2\msvc2019_64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      CMAKE_GENERATOR: "Visual Studio 17 2022"
      ENABLE_CYACAS_GUI: Off
      QTDIR: C:\Qt\5.15.2\msvc2022_64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      CMAKE_GENERATOR: "Ninja"
      ENABLE_CYACAS_GUI: Off
      QTDIR: $HOME/Qt/5.15.2/gcc_64/bin
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-bigsur
      CMAKE_GENERATOR: "Xcode"
      ENABLE_CYACAS_GUI: Off
      QTDIR: $HOME/Qt/5.15.2/clang_64/bin

before_build:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" -DENABLE_CYACAS_KERNEL=Off -DENABLE_CYACAS_UNIT_TESTS=Off -DENABLE_CYACAS_BENCHMARKS=Off -DENABLE_CYACAS_GUI=%ENABLE_CYACAS_GUI% -DCMAKE_PREFIX_PATH="%QTDIR%" -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\install
  - sh: cd $APPVEYOR_BUILD_FOLDER
  - sh: cmake -H. -Bbuild -G $CMAKE_GENERATOR -DCMAKE_BUILD_TYPE=Release -DENABLE_CYACAS_KERNEL=Off -DENABLE_CYACAS_UNIT_TESTS=Off -DENABLE_CYACAS_BENCHMARKS=Off -DENABLE_CYACAS_GUI=$ENABLE_CYACAS_GUI -DCMAKE_PREFIX_PATH="$QTDIR" -DCMAKE_INSTALL_PREFIX=$APPVEYOR_BUILD_FOLDER/install

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\build
  - cmd: cmake --build . --config Release --target install
  - sh: cd $APPVEYOR_BUILD_FOLDER/build
  - sh: cmake --build . --config Release --target install

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\build
  - cmd: ctest
  - sh: cd $APPVEYOR_BUILD_FOLDER/build
  - sh: ctest

after_build:
  - cmd: 7z a yacas.zip %APPVEYOR_BUILD_FOLDER%\install\*
  - sh: zip -r yacas.zip $APPVEYOR_BUILD_FOLDER/install/*

artifacts:
  - path: yacas.zip
    name: yacas

