branches:
  only:
    - master
    - develop

skip_tags: true

clone_script:
  - ps: >-
      if(-not $env:appveyor_pull_request_number) {
        $env:GIT_LFS_SKIP_SMUDGE = 1
        git clone -q --branch=$env:appveyor_repo_branch https://github.com/$env:appveyor_repo_name $env:appveyor_build_folder
        git checkout -qf $env:appveyor_repo_commit
        git lfs pull
      } else {
        $env:GIT_LFS_SKIP_SMUDGE = 1
        git clone -q https://github.com/$env:appveyor_repo_name $env:appveyor_build_folder
        git fetch -q origin +refs/pull/$env:appveyor_pull_request_number/merge:
        git checkout -qf FETCH_HEAD
        git lfs pull
      }

platform:
  - x64

configuration:
  - Release

image: Visual Studio 2017

environment:
  matrix:
    - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
      QTDIR: C:\Qt\5.13.2\msvc2017_64

before_build:
  - cd c:\projects\yacas
  - cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" -DENABLE_CYACAS_KERNEL=Off -DENABLE_CYACAS_UNIT_TESTS=Off -DENABLE_CYACAS_BENCHMARKS=Off  -DCMAKE_PREFIX_PATH="%QTDIR%" -DCMAKE_INSTALL_PREFIX=c:\projects\yacas\install

build:
  project: build\INSTALL.vcxproj

test_script:
  - cmd: msbuild "build\RUN_TESTS.vcxproj" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - 7z a yacas.zip c:\projects\yacas\install\*

artifacts:
  - path: yacas.zip
    name: yacas

