branches:
  only:
    - master

skip_tags: true

clone_folder: c:\projects\yacas

shallow_clone: true

platform:
  - x64

configuration:
  - Release

before_build:
  - echo Running cmake...
  - cd c:\projects\yacas
  - cmake -DCMAKE_INSTALL_PREFIX=%P% -G "Visual Studio 14 2015" 

build:
  project: ALL_BUILD.vcxproj

test_script:
  #- cmd: 'C:\projects\yacas\tests\test-yacas "C:\projects\yacas\Release\yacas.exe -pc --rootdir C:\projects\yacas\scripts" C:\projects\yacas\tests arithmetic.yts'
  - cmd: '"C:\Program Files (x86)\CMake\bin\ctest.exe" -C Release -VV --output-on-failure --debug'
  #- cmd: msbuild "RUN_TESTS.vcxproj" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
