name: yacas
version: 1.9.0-snap1
grade: stable
base: core18
summary: Yet Another Computer Algebra System
description: |
  Yacas is an easy to use, general purpose Computer Algebra System, a
  program for symbolic manipulation of mathematical expressions. It
  uses its own programming language designed for symbolic as well as
  arbitrary-precision numerical computations. The system has a library
  of scripts that implement many of the symbolic algebra operations;
  new algorithms can be easily added to the library.

confinement: strict

apps:
  yacas:
    command: yacas
    plugs: [home]
  gui:
    command: desktop-launch yacas-gui
    plugs: [home, x11, wayland, desktop, desktop-legacy, opengl, browser-support]
    environment:
      DISABLE_WAYLAND: 1
      QTWEBENGINEPROCESS_PATH: $RUNTIME/usr/lib/$ARCH/qt5/libexec/QtWebEngineProcess
      QT_QPA_PLATFORMTHEME: gtk3

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

build-packages:
  - g++
  - build-essential
  - python3-sphinx
  - python3-sphinx-rtd-theme
  - qtbase5-dev
  - libqt5webkit5-dev
  - libssl-dev
  - libboost-date-time-dev
  - libboost-program-options-dev
  - libjsoncpp-dev
  - dpkg-dev
  - git-lfs

parts:
  # Remote part for support of various desktop technologies
  # Refer: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt

    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5 # for loading icon themes which are svg
    - locales-all
    - xdg-user-dirs
    - qt5-gtk-platformtheme
  yacas:
    source: https://github.com/grzegorzmazur/yacas/archive/v1.9.0.tar.gz
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DENABLE_DOCS=On
    after: [desktop-qt5]
    build-packages:
      - libqt5svg5-dev
      - qtwebengine5-dev
      - libjsoncpp-dev
      - python3-sphinxcontrib.bibtex
    stage-packages:
      - qtwayland5
      - libqt5webengine5
      - libqt5webenginewidgets5
      - libqt5printsupport5
      - libqt5quickwidgets5
      - libjsoncpp1

layout:
    /usr/share/qt5:
        bind: $SNAP/usr/share/qt5